// <auto-generated />
using System;
using Banking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banking.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405074814_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Banking.Models.LoanAccount", b =>
                {
                    b.Property<string>("LoanId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Apr")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("DisbursedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Emi")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("LoanStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Outstanding")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.HasKey("LoanId");

                    b.ToTable("LoanAccounts");
                });

            modelBuilder.Entity("Banking.Models.LoanApplication", b =>
                {
                    b.Property<string>("ApplicationId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreditScore")
                        .HasColumnType("int");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId");

                    b.ToTable("LoanApplications");
                });

            modelBuilder.Entity("Banking.Models.LoanOffer", b =>
                {
                    b.Property<string>("OfferId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Apr")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Emi")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("OfferStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPayable")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("OfferId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("LoanOffers");
                });

            modelBuilder.Entity("Banking.Models.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("LoanId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PaymentRef")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("PaymentId");

                    b.HasIndex("LoanId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Banking.Models.RepaymentSchedule", b =>
                {
                    b.Property<string>("ScheduleId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Emi")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("InstallmentNo")
                        .HasColumnType("int");

                    b.Property<string>("InstallmentStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LoanId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ScheduleId");

                    b.HasIndex("LoanId");

                    b.ToTable("RepaymentSchedules");
                });

            modelBuilder.Entity("Banking.Models.LoanOffer", b =>
                {
                    b.HasOne("Banking.Models.LoanApplication", "LoanApplication")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoanApplication");
                });

            modelBuilder.Entity("Banking.Models.Payment", b =>
                {
                    b.HasOne("Banking.Models.LoanAccount", "LoanAccount")
                        .WithMany("Payments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoanAccount");
                });

            modelBuilder.Entity("Banking.Models.RepaymentSchedule", b =>
                {
                    b.HasOne("Banking.Models.LoanAccount", "LoanAccount")
                        .WithMany("RepaymentSchedules")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanAccount");
                });

            modelBuilder.Entity("Banking.Models.LoanAccount", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("RepaymentSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
